"""Name List"""
def main():
    """Main Function"""
    number = int(input())
    number = info(number)
    number = info(number)
    number = info(number)
    number = info(number)
    number = info(number)
    number = info(number)
    number = info(number)
    number = info(number)
    number = info(number)
    number = info(number)
    number = info(number)
    number = info(number)
    number = info(number)
    number = info(number)
    number = info(number)
    number = info(number)
    number = info(number)
    number = info(number)
    number = info(number)
    number = info(number)
    number = info(number)
    number = info(number)
    number = info(number)
    number = info(number)
    number = info(number)
    number = info(number)
    number = info(number)
    number = info(number)
    number = info(number)
    number = info(number)
    number = info(number)
    number = info(number)
    number = info(number)
    number = info(number)
    number = info(number)
    number = info(number)
    number = info(number)
    number = info(number)
    number = info(number)
    number = info(number)
    number = info(number)
    number = info(number)
    number = info(number)
    number = info(number)
    number = info(number)
    number = info(number)
    number = info(number)
    number = info(number)
    number = info(number)
    number = info(number)

def info(number):
    """Print Number"""
    print("ID#%i\t%s" % (number, input()))
    return number + 1

main()
