"""Name List"""
def main():
    """Main Function"""
    number = int(input())
    set1 = id(number, input(), 0)
    set2 = id(number, input(), 1)
    set3 = id(number, input(), 2)
    set4 = id(number, input(), 3)
    set5 = id(number, input(), 4)
    set6 = id(number, input(), 5)
    set7 = id(number, input(), 6)
    set8 = id(number, input(), 7)
    set9 = id(number, input(), 8)
    set10 = id(number, input(), 9)
    set11 = id(number, input(), 10)
    set12 = id(number, input(), 11)
    set13 = id(number, input(), 12)
    set14 = id(number, input(), 13)
    set15 = id(number, input(), 14)
    set16 = id(number, input(), 15)
    set17 = id(number, input(), 16)
    set18 = id(number, input(), 17)
    set19 = id(number, input(), 18)
    set20 = id(number, input(), 19)
    set21 = id(number, input(), 20)
    set22 = id(number, input(), 21)
    set23 = id(number, input(), 22)
    set24 = id(number, input(), 23)
    set25 = id(number, input(), 24)
    set26 = id(number, input(), 25)
    set27 = id(number, input(), 26)
    set28 = id(number, input(), 27)
    set29 = id(number, input(), 28)
    set30 = id(number, input(), 29)
    set31 = id(number, input(), 30)
    set32 = id(number, input(), 31)
    set33 = id(number, input(), 32)
    set34 = id(number, input(), 33)
    set35 = id(number, input(), 34)
    set36 = id(number, input(), 35)
    set37 = id(number, input(), 36)
    set38 = id(number, input(), 37)
    set39 = id(number, input(), 38)
    set40 = id(number, input(), 39)
    set41 = id(number, input(), 40)
    set42 = id(number, input(), 41)
    set43 = id(number, input(), 42)
    set44 = id(number, input(), 43)
    set45 = id(number, input(), 44)
    set46 = id(number, input(), 45)
    set47 = id(number, input(), 46)
    set48 = id(number, input(), 47)
    set49 = id(number, input(), 48)
    set50 = id(number, input(), 49)
    print(set1)
    print(set2)
    print(set3)
    print(set4)
    print(set5)
    print(set6)
    print(set7)
    print(set8)
    print(set9)
    print(set10)
    print(set11)
    print(set12)
    print(set13)
    print(set14)
    print(set15)
    print(set16)
    print(set17)
    print(set18)
    print(set19)
    print(set20)
    print(set21)
    print(set22)
    print(set23)
    print(set24)
    print(set25)
    print(set26)
    print(set27)
    print(set28)
    print(set29)
    print(set30)
    print(set31)
    print(set32)
    print(set33)
    print(set34)
    print(set35)
    print(set36)
    print(set37)
    print(set38)
    print(set39)
    print(set40)
    print(set41)
    print(set42)
    print(set43)
    print(set44)
    print(set45)
    print(set46)
    print(set47)
    print(set48)
    print(set49)
    print(set50)

def id(number, name, time):
    """Print info"""
    return "ID#%i\t%s" % ((number + time), name)

main()
